### ISSUE TITLE
Incompatible with Sodium/Indium and Embeddium on 1.20.4.

### ISSUE THREAD

**Issue by GoldenFurredFox** [HacktheTime/BingoNet#5]
Sodium/Indium and BBsentials crash log: https://mclo.gs/iQOn6tl

Embeddium and BBsentials crash log: https://mclo.gs/xGMgnvz

Game launches fine without BBsentials present and/or without Sodium/Indium or Embeddium present.

**Comment by GoldenFurredFox** [comment]
Didn't realize Sodium was on your incompatibilities list. Sorry.

**Comment by HacktheTime** [comment]
Dw. 

I put it on the incompatible list because it currently does not work with it.

I am not sure but you can try launching self-compiled version from hypeswap branch. I did some updates since the last modrinth push. Might work but not sure.

Also, there is a feature (numpad codes) which for some reason is currently incompatible with firmanent. It works single as well as when using both via development launch tools. It is just not going to work but there should not be any other major issues. Keep in mind that the mod is calling back to a server of mine and requires linking in the dc server to allow monitoring and use of some of its functions. 

If you notice any other bugs please make a bug report. Those are going to be useful. In different cases, it is useful to know how the issue occurred in the first place so make sure to at least memorize when the bug occurred so it may be able to be recreated.
